#! /usr/bin/env zsh -f

# Licence : NYSL (http://www.kmonos.net/nysl/)

setopt CDABLE_VARS

script_name=$0

function _zslot::help() {
cat <<EOS
NAME
    ${script_name} - named directory wrapper

SYNOPSIS
    ${script_name} [options] [name] [path]

DESCRIPTION
    Wrap named directory system in zsh.

    Following options (and parameters) are available:

    -a, --add
        USAGE:
            ${script_name} -a [name] [path]
            ${script_name} --add [name] [path]

    -u, --update
        USAGE:
            ${script_name} -u [old name] [new name]
            ${script_name} --update [old name] [new name]

    -d, --delete
        USAGE:
            ${script_name} -d [name]
            ${script_name} --delete [name]
EOS
}

function _zslot::validate_args() {
    local args=${*}
    local task=args[0]
    shift args

    local valid_tasks=(
        -a
        --add
        -u
        --update
        -d
        --delete
    )
    if [[ "${valid_tasks[(r)${task}]}" != "${task}" ]]; then;
        echo "[ERROR] Invalid task (${task}) was given" 1>&2
        return 1
    ; fi

    local n_required_args=2
    if [[ "${task}" == '-d' || "${task}" == '--delete' ]]; then
        n_required_args=1
    ; fi

    if [[ ${#args} != ${n_required_args} ]]; then;
        echo "[ERROR] Task ${task} requires ${n_required_args} of args" 1>&2
        return 1
    ; fi

    return 0
}

function _zslot::is_name_registered() {
    local name=${1}
    local record=$(hash -d | egrep "^${name}=.*$")

    if [[ -n ${record} ]]; then;
        return 0
    ; fi

    return 1
}

function _zslot::add() {
    local name=${1} dest=${2}

    _zslot::is_name_registered ${name}
    if [[ ${?} == 0 ]]; then;
        # TODO: Confirm overwrite or not.
    ; fi

    # TODO: Check path is exist or not.

    hash -d ${name}=${dest}
    return ${?}
}

function _zslot::update() {
    local old_name=${1} new_name=${2}
}

function _zslot::delete() {
    local name=${1}
}

function _zslot()
{
    local args=${*}
    local res=0

    _zslot::validate_args ${args}
    res=${?}
    if [[ ${res} != 0 ]]; then;
        _zslot::help
        return ${res}
    ; fi

    local args=${*}
    local task=args[0]
    shift args
    case ${task} in
        -a|--add)
            _zslot::add ${args}
            return ${?}
            ;;
        -u|--update)
            _zslot::update ${args}
            return ${?}
            ;;
        -d|--delete)
            _zslot::delete ${args}
            return ${?}
            ;;
    esac

    echo '[ERROR] Unknown error was occurred. Plase report in Github.' 1>&2
    return 1
}

_zslot $*

unset script_name
